# platform :ios, '1.0'

target 'RxSwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   # 函数响应式编程 https://github.com/ReactiveX/RxSwift
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  
  # 布局 https://github.com/SnapKit/SnapKit
   pod 'SnapKit'

end
